version: '3.7'

networks:
  fonoster:

services:
  metrics-ui:
    image: fonoster/metrics-ui:latest
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD", "echo", "test"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.metrics-ui.entrypoints=internal,websecure
      - traefik.http.routers.metrics-ui.rule=Host(`${LETSENCRYPT_DOMAIN}`) && PathPrefix(`${APP_BASE_PATH:-/metrics}`)
      - traefik.http.routers.metrics-ui.service=metrics-ui
      - traefik.http.services.metrics-ui.loadbalancer.server.port=3000
      - traefik.http.middlewares.metrics-ui-auth.basicauth.users=${JAEGER_USERNAME}:${JAEGER_PASSWORD_HASH}
      - traefik.http.middlewares.metrics-ui-chain.chain.middlewares=metrics-ui-auth
      - traefik.http.routers.metrics-ui.middlewares=metrics-ui-chain
    expose:
      - 3000
    environment:
      APP_URL: ${PUBLIC_URL}
      APP_BASE_PATH: /metrics
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      DS_SECRET: ${DS_SECRET}
      APISERVER_ENDPOINT: "apiserver.fonoster:50051"
      ALLOW_INSECURE: ${ALLOW_INSECURE}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
      LOGS_LEVEL: ${LOGS_LEVEL}
    networks:
      - fonoster
    volumes:
      - /opt/fonoster/operator/.env:/app/.env:ro
      - ${CONFIG}:/home/nextjs/.fonoster/config:ro
