version: '3.7'

networks:
  fonoster:

services:
  metrics-ui:
    image: efrafonoster/metrics-ui:latest
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD", "echo", "test"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.metrics-ui.entrypoints=internal,websecure
      - traefik.http.routers.metrics-ui.rule=Host(`${LETSENCRYPT_DOMAIN}`) && PathPrefix(`${APP_BASE_PATH:-/metrics}`)
      - traefik.http.routers.metrics-ui.service=metrics-ui
      - traefik.http.services.metrics-ui.loadbalancer.server.port=3000
    expose:
      - 3000
    environment:
      APP_URL: ${PUBLIC_URL}
      APP_BASE_PATH: /metrics
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      DS_SECRET: ${DS_SECRET}
      APISERVER_ENDPOINT: "apiserver.fonoster:50051"
      ALLOW_INSECURE: ${ALLOW_INSECURE}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
      LOGS_LEVEL: ${LOGS_LEVEL}
      SIPPROXY_API_HOST: ${SIPPROXY_API_HOST}
      SIPPROXY_API_PORT: ${SIPPROXY_API_PORT}
      SIPPROXY_API_USERNAME: ${SIPPROXY_API_USERNAME}
      SIPPROXY_API_SECRET: ${SIPPROXY_API_SECRET}
    networks:
      - fonoster
    # volumes:
    # - ${CONFIG}/.env:/app/.env:ro
    # - ${CONFIG}/config:/home/fonoster/.fonoster/config
    # - ${CONFIG}/config:/home/nextjs/.fonoster/config:ro
